### ISSUE TITLE
Allow fallback when no node is found

### ISSUE THREAD

**Issue by happenslol** [Wansmer/treesj#100]
I've looked through the readme, and it looks like right now it's only possible to add a fallback that will be used for buffers where treesitter is not present. However, I'd like to also have a fallback in cases where I do have treesitter, but no node is found.

The main use case for this would be literal strings that can't be parsed by tresitter, but still contain code that can be split/joined.

I'd be up for implementing this as well, what do you think about this feature?

**Comment by Wansmer** [comment]
This would be a useful improvement, thanks for the idea! If you are willing to do the implementation - feel free.

Please note that currently a recursive search for a suitable node is implemented, which only ends at the root node. Therefore, it makes sense to make the "fallback" field in the settings of each node, rather than a common one for all, to avoid false positives.

**Comment by Wansmer** [comment]
Done #125 and #124
