### ISSUE TITLE
Fallback to `mini.splitjoin`

### ISSUE THREAD

**Issue by savchenko** [Wansmer/treesj#143]
It would make sense to fall back onto `mini.splitjoin` if TreeSitter isn't configured for a buffer _or_ split operation fails.

For example, trying to split a long string in Bash returns:
```
[TreeSJ]: Node "string_content" for lang "bash" is not configured
```
...while the same line can be perfectly split by [mini.splitjoin](https://github.com/echasnovski/mini.splitjoin).

**Comment by Wansmer** [comment]
To add fallback for specific nodes, use the `fallback` option in the [node preset](https://github.com/Wansmer/treesj#basic-node) ([example of usage](https://github.com/Wansmer/treesj#option-fallback)).

Another way to add fallback to `mini.splitjoin` is how I [personally](https://github.com/Wansmer/nvim-config/blob/fbfadeaeccaa01414a6e97e10fe0328fad037156/lua/config/plugins/treesj.lua#L108-L116) use it.

Since both solutions depend on a third-party plugin, I will not to add this to the default configuration. API methods will do.
