### ISSUE TITLE
Bug: Splitting an array adds a trailing comma, even in languages where that is not valid

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#28]
Adding a trailing comma is actually a nice touch, but it's also applied in languages where a dangling comma is invalid, like js.

<img width="390" alt="Pasted image 2022-11-30 00 10 11" src="https://user-images.githubusercontent.com/73286100/204668490-70e9f052-5d85-4eb2-abd0-1746714897da.png">

<img width="856" alt="Pasted image 2022-11-30 00 07 54" src="https://user-images.githubusercontent.com/73286100/204668238-d70224ab-6471-40a3-83b9-df094d5dae36.png">

**Comment by Wansmer** [comment]
It's not a bug – you can change adding trailing comma with[ option](https://github.com/Wansmer/treesj#nodes-configuration) 'last_separator' in preset for 'array' node.
Btw, it is valid javascript - you have error because you have rule  '[comma-dangle](https://eslint.org/docs/latest/rules/comma-dangle)' in your `.eslintrc`. This rule actual only for IE8.

**Comment by chrisgrieser** [comment]
huh, TIL. with trailing commas being invalid in JSON, I always thought they were invalid in javascript as well.

Sorry for the irrelevant bug report then!
