### ISSUE TITLE
[feat] add ruby support

### ISSUE THREAD

**Issue by smarquez1** [Wansmer/treesj#6]
Great work! Just wanted to create this ticket so I can track the feature. Currently I'm using splitjoin.vim but I'd love to switch to a lua based plugin that supports treesitter

**Comment by Wansmer** [comment]
Hi! I added basic structures (hash, array, parameters, arguments) for ruby with #24.
I am not sure about another ruby nodes valid syntax (e.g., `statement_block` and `body_block` in methods), because I not a ruby user. You can help and open PR with configuration for other needed nodes, or send examples with code ([like here](https://github.com/Wansmer/treesj/blob/main/tests/sample/index.rb)).

**Comment by iovis** [comment]
Hi @Wansmer! A very useful one that I just found out treesj doesn't support coming from splitjoin is module namespaces.

Basically the idea is, if I have:
```rb
module Inputs
  class Base < GraphQL::Schema::InputObject
    field :something, String
  end
end
```
It is possible to join like:
```rb
# notice it's now <module name>::<class name>
class Inputs::Base < GraphQL::Schema::InputObject
  field :something, String
end
```
Splitjoin has a few tests that I think are good examples (I purposefully removed the `RSpec` ones at the bottom because I think those are quite rare, or at least I haven't seen them much):
https://github.com/AndrewRadev/splitjoin.vim/blob/main/spec/plugin/ruby_spec.rb#L59-L173

I'm not sure if it's feasible —and definitely not as common of a split/join—, but I do use it from time to time. If you think it helps, I can open a new issue or a PR with the code examples translated to the file you linked (https://github.com/Wansmer/treesj/blob/main/tests/sample/index.rb)

**Comment by Wansmer** [comment]
Hi @iovis!
> I'm not sure if it's feasible —and definitely not as common of a split/join—, but I do use it from time to time. If you think it helps, I can open a new issue or a PR with the code examples translated to the file you linked 

Yes, please, open issue with real-life examples of code. I will check its tree, and if it's possible to setting, to add to the ruby preset.

**Comment by iovis** [comment]
Created an issue to track here: https://github.com/Wansmer/treesj/issues/81
